// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbxsfovtxlgusgwlynge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJieHNmb3Z0eGxndXNnd2x5bmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjQ4MDYsImV4cCI6MjA3MzQ0MDgwNn0.qnXkAU0M_rsTq7ZUainZAOrOaMciKoKvEpvv77jwczU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});